blank_issues_enabled: false
contact_links
  - name Argentum Online Code of Conduct
    url https://dev.comunidadargentum.com/code-of-conduct
    about Please report security vulnerabilities here.
  - name Argentum Online Security Vulnerability Reports
    url https://dev.comunidadargentum.com/security
    about Please report security vulnerabilities here.  
  - name Argentum Online Community Forums
    url http://foro.comunidadargentum.com
    about Forums to intectact with the entire community
  - name Argentum Online Discord Server
    url https://discord.gg/argentumonline
    about Discord server to chat with the team and the community
