blank_issues_enabled: false
contact_links
  - name Argentum Online - Alkon - Code of Conduct
    url https://dev.alkononline.com.ar/code-of-conduct
    about Please report security vulnerabilities here.
  - name Argentum Online Security Vulnerability Reports
    url https://dev.alkononline.com.ar/security
    about Please report security vulnerabilities here.  
  - name Argentum Online - Alkon - Website
    url https://www.alkononline.com.ar
    about Website
  - name Argentum Online Discord Server
    url https://discord.gg/argentumonline
    about Discord server to chat with the team and the community
